baseURL = "https://nam19062005.github.io/Nguyen_Ba_Nam_Workshop_AWS/"
relativeURLs = true
canonifyURLs = true
defaultContentLanguage = "vi"

# Default theme for Hugo Learn Theme
theme = "hugo-theme-learn"

# Outputs for search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Theme color scheme: "workshop", "blue", "red", "green"
  themeVariant = "workshop"
  editURL = ""
  description = "Báo cáo thực tập & Workshop - Nguyễn Bá Nam (AWS FCJ)"
  author = "Nguyen Ba Nam"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[Languages.vi]
title = "Báo cáo thực tập - Nguyễn Bá Nam"
weight = 1
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[Languages.en]
title = "Internship Report - Nguyen Ba Nam"
weight = 2
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
