name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true        # <-- BẮT BUỘC: checkout theme submodule
          fetch-depth: 0          # Lấy toàn bộ lịch sử git

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.134.3"
          extended: true

      - name: Build website
        run: hugo --minify --baseURL "https://nam19062005.github.io/Nguyen_Ba_Nam_Workshop_AWS/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
